### ISSUE TITLE
field base has errors: no_rate_chosen

### ISSUE THREAD

**Issue by NicoJuicy** [NicoJuicy/WeAreWuunder.Api#1]
This is the response after doing a dummy request to Wuunder

**Comment by NicoJuicy** [comment]
Awaiting feedback from Wuunder

**Comment by JeroenGehlen** [comment]
This means there are no or not the desired carrier connected to your account. Can you let me know via info@wearewuunder.com what service / carrier you are trying to book and your username and I'll enable these services asap. Thanks

**Comment by NicoJuicy** [comment]
@JeroenGehlen i was not expecting response here on my own repo ( i'll add notifications). 
I'm in contact with the support which is going fine for now. 

Just resolving some things with hs-code before i can update this repo.

**Comment by NicoJuicy** [comment]
no_rate_chosen seems to be a generic error when something goes wrong.

In this case, both pickup address & delivery address were required.
Removing the pickup address fixed the issues.
